import { Config, DataSourceConfig } from "integration-huron-person";
import { ENVIRONMENT_VARIABLES_NAMES, SourceSimulatorFunctionURL, getSimulatorCounter, FUNCTION_BASE_NAME as sourceSimulatorFunctionBaseName } from "../../chunking/fetch/SourceSimulator";
import { ChunkingServiceRunner } from "../AbstractRunner";
import { LambdaFunctionEnvironmentVariable } from "../LambdaFunctionEnvironmentVariable";
import { Endpoint, NormalizedPopulationType, TargetConfig } from "../RunnerTypes";

/**
 * Decorator that uses the source simulator if enabled in the environment. This should 
 * automatically prevent processing of chunk files once they have been generated by 
 * disabling the processor service.
 */
export class SourceSimulatorRunnerDecorator extends ChunkingServiceRunner {
  constructor(private readonly wrappedRunner: ChunkingServiceRunner) {
    super();
  }
  public async validatePrerequisites(): Promise<boolean> {
    let { 
      region, landscape, messagesToPrepopulate, iterationLimit, 
      sourceSimulatorMockSimulatedDelaySeconds: delay, 
      sourceSimulatorMockTotalPopulation: total,
      sourceSimulatorMockErrorRate: errorRate
    } = this.wrappedRunner.env;

    const { 
      MOCK_TOTAL_POPULATION, MOCK_ERROR_RATE, MOCK_SIMULATED_DELAY_SECONDS 
    } = ENVIRONMENT_VARIABLES_NAMES;

    // Check if the source simulator lambda function URL exists before proceeding. 
    const sourceSimulatorFunctionUrl = new SourceSimulatorFunctionURL({ landscape: landscape!, region: region! });
    if( ! await sourceSimulatorFunctionUrl.exists() ) {
      console.error(`Source simulator function URL does not exist for landscape ${landscape} in region ${region}. Please ensure the source simulator is deployed and the function URL is created.`);
      return false;
    }
    
    // Singleton logic for getting an instance of the utility for modifying Lambda function environment variables. 
    let lambda: LambdaFunctionEnvironmentVariable | null = null;
    const getSourceSimulatorLambdaFunction = async () => {
      if (!lambda) {
        lambda = new LambdaFunctionEnvironmentVariable({ 
          lambdaFunctionName: `${sourceSimulatorFunctionBaseName}-${landscape}`, region: region! 
        });
      }
      return lambda;
    }

    // Update all simulator environment overrides in one Lambda configuration update.
    // This avoids back-to-back update conflicts when multiple values are provided.
    const sourceSimulatorEnvOverrides: Record<string, string> = {};
    if(delay && delay > 0) {
      sourceSimulatorEnvOverrides[MOCK_SIMULATED_DELAY_SECONDS] = delay.toString();
    }
    if(total && total > 0) {
      sourceSimulatorEnvOverrides[MOCK_TOTAL_POPULATION] = total.toString();
    }
    if(errorRate && errorRate > 0) {
      sourceSimulatorEnvOverrides[MOCK_ERROR_RATE] = errorRate.toString();
    }
    if(Object.keys(sourceSimulatorEnvOverrides).length > 0) {
      const lambda = await getSourceSimulatorLambdaFunction();
      await lambda.setEnvironmentVariables(sourceSimulatorEnvOverrides);
    }

    const getNbrFromStr = (val: string | undefined): number => val && !isNaN(Number(val)) ? parseInt(val) : 0;

    const getNbr = (nbr: number | undefined): number => nbr && !isNaN(nbr) ? nbr : 0;
    
    // Warn if queue seeding is being carried out that we are not overseeding as determined by
    // comparing the seedNumber math to source simulator predicted population. 
    if (getNbrFromStr(messagesToPrepopulate) > 0 ) { 
      const seedNumber = parseInt(messagesToPrepopulate);

      if(seedNumber > 0) {
        const predictions = await this.getSourceSimulatorPredictions();
        const { totalPopulation, itemsPerChunk } = predictions;
        iterationLimit = getNbr(iterationLimit);
        const singleTaskPopulation = iterationLimit * itemsPerChunk;
        if(singleTaskPopulation >= 0) {
          const seedingPopulation = seedNumber * itemsPerChunk * iterationLimit;
          
          if(seedingPopulation > totalPopulation) {
            const overage = seedingPopulation - totalPopulation;
            if(overage > singleTaskPopulation) {
              console.warn(`Overseeding: Seeding population (${seedingPopulation}) exceeds total population (${totalPopulation}) by more than a single task's worth of items (${singleTaskPopulation}).`);
            }
          }
          else {
            console.log(`Seeding population (${seedingPopulation}) is within the total population (${totalPopulation}). Proceeding with operation.`);
          }
        }
      }
    }


    return this.wrappedRunner.validatePrerequisites();
  }

  public async resolveDataSource(config: Config): Promise<Endpoint> {
    const { region, landscape, sourceSimulator, stackId } = this.wrappedRunner.env;
    let { 
      endpointConfig: { baseUrl } = {}, 
      fetchPath 
    } = config.dataSource?.people as DataSourceConfig || {};

    if(!sourceSimulator) {
      console.log('Source simulator not enabled. Using configured endpoint.');
      return { baseUrl: baseUrl!, fetchPath: fetchPath! };
    }

    // Use source simulator if enabled
    if (!region || !landscape) {
      throw new Error('REGION and LANDSCAPE are required to use source simulator');
    }

    const sourceSimulatorFunctionUrl = new SourceSimulatorFunctionURL({ landscape, region });
    const functionUrlObj = new URL(await sourceSimulatorFunctionUrl.getUrl());
    baseUrl = `${functionUrlObj.protocol}//${functionUrlObj.host}`;
    fetchPath = functionUrlObj.pathname;
    
    console.log(`Using source simulator: ${JSON.stringify({ baseUrl, fetchPath }, null, 2)}`);

    await this.logSourceSimulatorPredictions();

    // Reset the atomic counter for the source simulator to ensure a clean state before starting the operation. This is important to avoid any residual state from previous runs affecting the current operation.
    const atomicCounter = getSimulatorCounter({ stackId, region, landscape });
    console.log(`Resetting source simulator atomic counter for landscape ${landscape} in region ${region}.`);
    if(!atomicCounter) {
      throw new Error('Unable to get atomic counter for source simulator. Ensure STACK_ID, REGION, and LANDSCAPE are set.');
    }
    await atomicCounter.reset();

    return { baseUrl: baseUrl!, fetchPath: fetchPath! };
  }

  public async resolveDataTarget(config: Config): Promise<TargetConfig> {
    return this.wrappedRunner.resolveDataTarget(config);
  }

  public async execute(
    sourceEndpoint: Endpoint,
    targetConfig: TargetConfig,
    config: Config,
    populationType: NormalizedPopulationType
  ): Promise<void> {
    return this.wrappedRunner.execute(sourceEndpoint, targetConfig, config, populationType);
  }
}