import { Config, DataSourceConfig } from "integration-huron-person";
import { ENVIRONMENT_VARIABLES_NAMES, SourceSimulatorFunctionURL, FUNCTION_BASE_NAME as sourceSimulatorFunctionBaseName } from "../../chunking/fetch/SourceSimulator";
import { ChunkingServiceRunner } from "../AbstractRunner";
import { LambdaFunctionEnvironmentVariable } from "../LambdaFunctionEnvironmentVariable";
import { Endpoint, NormalizedPopulationType } from "../RunnerTypes";

/**
 * Decorator that uses the source simulator if enabled in the environment. This should 
 * automatically prevent processing of chunk files once they have been generated by 
 * disabling the processor service.
 */
export class SourceSimulatorRunnerDecorator extends ChunkingServiceRunner {
  constructor(private readonly wrappedRunner: ChunkingServiceRunner) {
    super();
  }
  public async validatePrerequisites(): Promise<boolean> {
    const { 
      region, landscape, 
      sourceSimulatorMockSimulatedDelaySeconds: delay, 
      sourceSimulatorMockTotalPopulation: total,
      sourceSimulatorMockErrorRate: errorRate
    } = this.wrappedRunner.env;

    const { 
      MOCK_TOTAL_POPULATION, MOCK_ERROR_RATE, MOCK_SIMULATED_DELAY_SECONDS 
    } = ENVIRONMENT_VARIABLES_NAMES;

    // Check if the source simulator lambda function URL exists before proceeding. 
    const sourceSimulatorFunctionUrl = new SourceSimulatorFunctionURL({ landscape: landscape!, region: region! });
    if( ! await sourceSimulatorFunctionUrl.exists() ) {
      console.error(`Source simulator function URL does not exist for landscape ${landscape} in region ${region}. Please ensure the source simulator is deployed and the function URL is created.`);
      return false;
    }
    
    // Singleton logic for getting an instance of the utility for modifying Lambda function environment variables. 
    let lambda: LambdaFunctionEnvironmentVariable | null = null;
    const getSourceSimulatorLambdaFunction = async () => {
      if (!lambda) {
        lambda = new LambdaFunctionEnvironmentVariable({ 
          lambdaFunctionName: `${sourceSimulatorFunctionBaseName}-${landscape}`, region: region! 
        });
      }
      return lambda;
    }

    // Update the source simulator Lambda function's environment variables if they are provided in the configuration.
    if(delay && delay > 0) {
      const lambda = await getSourceSimulatorLambdaFunction();
      await lambda.setEnvironmentVariable(MOCK_SIMULATED_DELAY_SECONDS, delay.toString());
    }
    if(total && total > 0) {
      const lambda = await getSourceSimulatorLambdaFunction();
      await lambda.setEnvironmentVariable(MOCK_TOTAL_POPULATION, total.toString());
    }
    if(errorRate && errorRate > 0) {
      const lambda = await getSourceSimulatorLambdaFunction();
      await lambda.setEnvironmentVariable(MOCK_ERROR_RATE, errorRate.toString());
    }

    return this.wrappedRunner.validatePrerequisites();
  }

  public async resolveDataSource(config: Config): Promise<Endpoint> {
    const { region, landscape, sourceSimulator } = this.wrappedRunner.env;
    let { 
      endpointConfig: { baseUrl } = {}, 
      fetchPath 
    } = config.dataSource?.people as DataSourceConfig || {};

    if(!sourceSimulator) {
      console.log('Source simulator not enabled. Using configured endpoint.');
      return { baseUrl: baseUrl!, fetchPath: fetchPath! };
    }

    // Use source simulator if enabled
    if (!region || !landscape) {
      throw new Error('REGION and LANDSCAPE are required to use source simulator');
    }

    const sourceSimulatorFunctionUrl = new SourceSimulatorFunctionURL({ landscape, region });
    const functionUrlObj = new URL(await sourceSimulatorFunctionUrl.getUrl());
    baseUrl = `${functionUrlObj.protocol}//${functionUrlObj.host}`;
    fetchPath = functionUrlObj.pathname;
    
    console.log(`Using source simulator: ${JSON.stringify({ baseUrl, fetchPath }, null, 2)}`);

    await this.logSourceSimulatorPredictions();

    return { baseUrl: baseUrl!, fetchPath: fetchPath! };
  }

  public async execute(endpoint: Endpoint, config: Config, populationType: NormalizedPopulationType): Promise<void> {
    return this.wrappedRunner.execute(endpoint, config, populationType);
  }
}